(()=>{
const id=location.pathname.split('/').filter(Boolean)[2]||'fcu1',api=`/mrsmart/fcu/${id}/api`,isCast=document.body.classList.contains('cast');
let M={},S={},E=[],editing=false,scheduleDraft={},activeDay='monday',weeklyOpen=true,installerOpen=false,pending={};
const $=s=>document.querySelector(s),h=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function set(p,v){if(!p)return;try{let r=await fetch(api+'/set',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({property:p,value:v})});if(!r.ok)throw new Error('Command failed: HTTP '+r.status)}catch(e){throw e}}async function waitState(p,v,timeout=7000){let end=Date.now()+timeout;while(Date.now()<end){try{let z=await(await fetch(api+'/state',{cache:'no-store'})).json(),x=(z.state||{})[p];if(String(x)===String(v))return true}catch{}await new Promise(r=>setTimeout(r,350))}return false}
function prop(a){return a.find(n=>Object.hasOwn(S,n)||E.some(e=>e.property===n))||null}function ex(p){return E.find(e=>e.property===p)||{}}function val(p,d='--'){return p&&pending[p]?pending[p].value:(p?(S[p]??d):d)}function v(a,d='--'){let p=prop(a);return p?val(p,d):d}function reconcilePending(){for(const p of Object.keys(pending))if(String(S[p])===String(pending[p].value))delete pending[p]}function isOn(x,e={}){return x===e.value_on||['ON','on','LOCK','OPEN',true,1].includes(x)}
function buttons(sel,p,vals,icons={}){let q=$(sel);if(!q)return;let castName=x=>isCast?({off:'OFF',cool:'COOL',heat:'HEAT',fan_only:'FAN',low:'LOW',medium:'MED',high:'HIGH',auto:'AUTO'}[String(x)]||String(x).toUpperCase()):`${icons[x]||''} ${h(x)}`;q.innerHTML=p?vals.map(x=>`<button data-p="${h(p)}" data-v="${h(x)}" class="${String(val(p))===String(x)?'active':''}">${castName(x)}</button>`).join(''):'<span class="small">N/A</span>'}
function binaryCtl(e,x){let on=e.value_on!==undefined?e.value_on:'ON',off=e.value_off!==undefined?e.value_off:'OFF',known=x!=='--';return `<div class="binaryPair"><button data-p="${h(e.property)}" data-json="${h(JSON.stringify(off))}" class="${known&&String(x)===String(off)?'active':''}">${h(off)}</button><button data-p="${h(e.property)}" data-json="${h(JSON.stringify(on))}" class="${known&&String(x)===String(on)?'active':''}">${h(on)}</button></div>`}
function dynamicCtl(e){let x=S[e.property]??'--',w=(e.access&2)===2;if(!w)return `<div class="ctrl readonly">${h(x)}${x!=='--'&&e.unit?h(e.unit):''}</div>`;if(e.values)return `<select data-select="${h(e.property)}"><option value="" disabled ${x==='--'?'selected':''}>Select…</option>${e.values.map(y=>`<option ${String(y)===String(x)?'selected':''}>${h(y)}</option>`).join('')}</select>`;if(e.type==='binary')return binaryCtl(e,x);if(e.type==='numeric'){let min=e.value_min,max=e.value_max,step=e.value_step??'any';return `<div class="numberCtl"><input inputmode="decimal" type="text" autocomplete="off" data-num="${h(e.property)}" value="${x==='--'?'':h(x)}" ${min!=null?`min="${min}"`:''} ${max!=null?`max="${max}"`:''} step="${step}"><span>${h(e.unit||'')}</span><button class="applyNum" data-num-send="${h(e.property)}">Apply</button></div><div class="rangeHint">${min!=null&&max!=null?`${min} – ${max}${e.unit?' '+h(e.unit):''}`:''}${e.value_step!=null?` · step ${e.value_step}`:''}</div>`}return `<div class="ctrl">${h(x)}</div>`}
const scheduleProps=['monday','tuesday','wednesday','thursday','friday','saturday','sunday'];
function parseSchedule(str){let a=String(str||'').trim().split(/\s+/).filter(Boolean).map(x=>{let [time,temp]=x.split('/');return {time:/^\d\d:\d\d$/.test(time||'')?time:'',temp:temp??''}});if(!a.length)a=[{time:'06:00',temp:'20.0'},{time:'11:30',temp:'20.0'},{time:'13:30',temp:'20.0'},{time:'17:30',temp:'20.0'}];return a}
function ensureDraft(day){let p='schedule_'+day;if(!scheduleDraft[day])scheduleDraft[day]=parseSchedule(S[p])}
function scheduleHTML(){ensureDraft(activeDay);let rows=scheduleDraft[activeDay];return `<div class="dayTabs">${scheduleProps.map(d=>`<button type="button" data-day="${d}" class="${d===activeDay?'active':''}">${d.slice(0,3).toUpperCase()}</button>`).join('')}</div><div class="periods">${rows.map((r,i)=>`<div class="period"><b>P${i+1}</b><input type="time" step="60" autocomplete="off" data-sch-time="${i}" value="${h(r.time)}"><input type="number" inputmode="decimal" autocomplete="off" min="5" max="35" step="0.5" data-sch-temp="${i}" value="${h(r.temp)}" placeholder="°C"></div>`).join('')}</div><div class="scheduleMode"><span class="small">Schedule mode: <b>${S.manual_mode==='OFF'?'ACTIVE':S.manual_mode==='ON'?'INACTIVE (MANUAL)':'UNKNOWN'}</b></span>${E.some(e=>e.property==='manual_mode'&&(e.access&2)===2)?`<button type="button" data-toggle-schedule="1" class="${S.manual_mode==='OFF'?'active':''}">${S.manual_mode==='OFF'?'Disable Schedule':'Enable Schedule'}</button>`:''}</div><div class="scheduleActions"><span id="scheduleMsg" class="small"></span><button type="button" data-save-schedule="1">Save ${activeDay[0].toUpperCase()+activeDay.slice(1)}</button></div>`}
function installerHTML(){let reserved=new Set(['local_temperature','current_temperature','temperature','current_heating_setpoint','target_temperature','occupied_heating_setpoint','occupied_cooling_setpoint','state','power','system_power','system_mode','mode','fan_mode','fan_speed','speed','valve','manual_mode','linkquality',...scheduleProps.map(d=>'schedule_'+d)]);let list=E.filter(e=>!reserved.has(e.property)&&e.category!=='diagnostic');return list.map(e=>`<div class="dyn"><div class="dynHead"><div class="dynName">${h(e.label||e.name||e.property)}</div>${e.description?`<div class="hint">${h(e.description)}</div>`:''}</div>${dynamicCtl(e)}</div>`).join('')||'<span class="small">No installer settings exposed.</span>'}
function renderDynamic(force=false){if(isCast)return;let dy=$('#dynamic');if(!dy)return;let focus=document.activeElement;if(!force&&focus&&dy.contains(focus)&&focus.matches('input,select'))return;dy.innerHTML=`<details class="fold" data-fold="weekly" ${weeklyOpen?'open':''}><summary>Weekly schedule</summary><div class="foldBody">${scheduleHTML()}</div></details><details class="fold" data-fold="installer" ${installerOpen?'open':''}><summary>Installer settings</summary><div class="foldBody">${installerHTML()}</div></details>`}
function render(){let c=$('#conn');if(c)c.textContent=M.connected?`● Connected · ${M.deviceTopic||'discovering'}`:'○ MQTT disconnected';let cur=$('#current');if(cur)cur.textContent=v(['local_temperature','current_temperature','temperature'])+'°';let sp=prop(['current_heating_setpoint','target_temperature','occupied_heating_setpoint','occupied_cooling_setpoint']),sv=$('#setval');if(sv)sv.textContent=sp?(S[sp]??'--')+'°':'--';let pw=prop(['state','power','system_power']),pe=ex(pw),on=pw&&isOn(S[pw],pe),pb=$('#power'),pc=$('#powerCard');if(pc)pc.hidden=!pw;if(pb)pb.classList.toggle('active',!!on);let pt=$('#powerText');if(pt)pt.textContent=pw?(S[pw]??'--'):'--';let md=prop(['system_mode','mode']),me=ex(md);buttons('#modes',md,me.values||['off','cool','heat','fan_only'],{cool:'❄',heat:'♨',fan_only:'◉',auto:''});let fn=prop(['fan_mode','fan_speed','speed']),fe=ex(fn);buttons('#fans',fn,fe.values||['low','medium','high','auto'],{auto:'',low:'◔',medium:'◑',high:'●'});let valve=v(['valve'],null),mode=v(['system_mode','mode'],null),run='--';if(valve==='OPEN')run=mode==='heat'?'HEATING':mode==='cool'?'COOLING':mode==='fan_only'?'FAN':'ACTIVE';else if(valve==='CLOSE')run='IDLE';let rr=$('#running');if(rr)rr.textContent=run;document.body.classList.remove('mode-cool','mode-heat','mode-fan','mode-off');document.body.classList.add(mode==='cool'?'mode-cool':mode==='heat'?'mode-heat':mode==='fan_only'?'mode-fan':'mode-off');let aa=$('#arcActive'),ab=$('#arcBg'),kn=$('#dialKnob');if(aa&&ab&&kn&&sp){let se=ex(sp),mn=se.value_min??5,mx=se.value_max??35,val=+(S[sp]??mn),pct=Math.max(0,Math.min(1,(val-mn)/(mx-mn)));let cx=150,cy=150,r=112,start=135,end=405,polar=a=>{let q=(a-90)*Math.PI/180;return[cx+r*Math.cos(q),cy+r*Math.sin(q)]},path=(a0,a1)=>{let A=polar(a0),B=polar(a1),large=(a1-a0)>180?1:0;return`M ${A[0]} ${A[1]} A ${r} ${r} 0 ${large} 1 ${B[0]} ${B[1]}`};ab.setAttribute('d',path(start,end));let ang=start+pct*(end-start);aa.setAttribute('d',path(start,ang));let K=polar(ang);kn.setAttribute('cx',K[0]);kn.setAttribute('cy',K[1])}renderDynamic()}
function validNum(input,e){let x=Number(input.value);if(!Number.isFinite(x))return null;if(e.value_min!=null&&x<e.value_min)return null;if(e.value_max!=null&&x>e.value_max)return null;if(e.value_step!=null&&e.value_min!=null){let n=Math.round((x-e.value_min)/e.value_step)*e.value_step+e.value_min;if(Math.abs(n-x)>1e-7)return null}return x}
document.addEventListener('toggle',e=>{let d=e.target;if(!d.matches||!d.matches('details[data-fold]'))return;if(d.dataset.fold==='weekly')weeklyOpen=d.open;if(d.dataset.fold==='installer')installerOpen=d.open},true);
document.addEventListener('focusin',e=>{if(e.target.matches('input,select'))editing=true});document.addEventListener('focusout',e=>{if(e.target.matches('input,select'))setTimeout(()=>editing=false,100)});
document.addEventListener('input',e=>{if(e.target.dataset.schTime!==undefined){ensureDraft(activeDay);scheduleDraft[activeDay][+e.target.dataset.schTime].time=e.target.value}if(e.target.dataset.schTemp!==undefined){ensureDraft(activeDay);scheduleDraft[activeDay][+e.target.dataset.schTemp].temp=e.target.value}});
document.addEventListener('click',async e=>{let b=e.target.closest('[data-p]');if(b){let val=b.dataset.json!==undefined?JSON.parse(b.dataset.json):b.dataset.v;await set(b.dataset.p,val)}let d=e.target.closest('[data-day]');if(d){activeDay=d.dataset.day;renderDynamic(true);return}let ns=e.target.closest('[data-num-send]');if(ns){let p=ns.dataset.numSend,i=document.querySelector(`[data-num="${CSS.escape(p)}"]`),ee=ex(p),x=validNum(i,ee);if(x===null){i.classList.add('invalid');return}i.classList.remove('invalid');await set(p,x)}let es=e.target.closest('[data-toggle-schedule]');if(es){let m=$('#scheduleMsg'),currentlyActive=S.manual_mode==='OFF',target=currentlyActive?'ON':'OFF';if(m)m.textContent=currentlyActive?'Disabling schedule…':'Enabling schedule…';await set('manual_mode',target);let ok=await waitState('manual_mode',target);if(ok){S.manual_mode=target;if(m)m.textContent=target==='OFF'?'Schedule enabled and confirmed by thermostat.':'Schedule disabled; manual setpoint control restored.';renderDynamic(true)}else if(m)m.textContent='Command sent; no thermostat confirmation yet.';return}let ss=e.target.closest('[data-save-schedule]');if(ss){ensureDraft(activeDay);let rows=scheduleDraft[activeDay],validTime=x=>/^([01]\d|2[0-3]):[0-5]\d$/.test(String(x).trim()),validTemp=x=>String(x).trim()!==''&&Number.isFinite(Number(x))&&Number(x)>=5&&Number(x)<=35&&Math.abs(Number(x)*2-Math.round(Number(x)*2))<1e-7;let m=$('#scheduleMsg');if(rows.some(r=>!validTime(r.time)||!validTemp(r.temp))){if(m)m.textContent='Complete all displayed periods: valid time and 5–35°C in 0.5°C steps.';return}let mins=rows.map(r=>{let [hh,mm]=r.time.split(':').map(Number);return hh*60+mm});if(mins.some((x,i)=>i&&x<=mins[i-1])){if(m)m.textContent='Period times must be in increasing order.';return}let value=rows.map(r=>`${String(r.time).trim()}/${Number(r.temp).toFixed(1)}`).join(' '),p='schedule_'+activeDay;if(m)m.textContent='Sending to thermostat…';await set(p,value);let ok=await waitState(p,value);if(ok){S[p]=value;if(m)m.textContent='Saved and confirmed by thermostat.'}else if(m)m.textContent='Command sent; no matching thermostat confirmation yet.';return}});
document.addEventListener('change',e=>{if(e.target.dataset.select)set(e.target.dataset.select,e.target.value)});
let power=$('#power');if(power)power.onclick=()=>{let p=prop(['state','power','system_power']),e=ex(p);if(p)set(p,isOn(S[p],e)?(e.value_off??'OFF'):(e.value_on??'ON'))};for(const [id,d] of [['minus',-1],['plus',1]]){let q=$('#'+id);if(q)q.onclick=()=>{let p=prop(['current_heating_setpoint','target_temperature','occupied_heating_setpoint','occupied_cooling_setpoint']);if(p){let e=ex(p),nv=+(S[p]??20)+d*(e.value_step??.5);set(p,Math.max(e.value_min??5,Math.min(e.value_max??35,nv)))}}}
function dialValue(ev){let p=prop(['current_heating_setpoint','target_temperature','occupied_heating_setpoint','occupied_cooling_setpoint']);if(!p)return null;let svg=$('#dialSvg'),r=svg.getBoundingClientRect(),x=(ev.clientX-r.left)/r.width*300,y=(ev.clientY-r.top)/r.height*300,dx=x-150,dy=y-150,deg=Math.atan2(dy,dx)*180/Math.PI+90;if(deg<0)deg+=360;if(deg<135)deg+=360;deg=Math.max(135,Math.min(405,deg));let e=ex(p),mn=e.value_min??5,mx=e.value_max??35,step=e.value_step??.5,nv=mn+((deg-135)/270)*(mx-mn);nv=Math.round((nv-mn)/step)*step+mn;return{p,v:Math.max(mn,Math.min(mx,+nv.toFixed(3)))}}
let ds=$('#dialSvg'),drag=false,lastSent=0;function previewDial(ev,commit=false){let q=dialValue(ev);if(!q)return;let sv=$('#setval');if(sv)sv.textContent=q.v+'°';let now=Date.now();if(commit||now-lastSent>120){lastSent=now;set(q.p,q.v)}}if(ds){ds.addEventListener('pointerdown',e=>{drag=true;ds.setPointerCapture?.(e.pointerId);previewDial(e,true)});ds.addEventListener('pointermove',e=>{if(drag)previewDial(e)});ds.addEventListener('pointerup',e=>{if(drag){previewDial(e,true);drag=false}});ds.addEventListener('pointercancel',()=>drag=false)}
async function poll(){try{M=await(await fetch(api+'/state',{cache:'no-store'})).json();S=M.state||{};E=M.exposes||[];reconcilePending();render()}catch{let c=$('#conn');if(c)c.textContent='○ UI unavailable'}}
function startEvents(){if(!window.EventSource)return;try{let es=new EventSource(api+'/events');es.addEventListener('state',ev=>{try{let z=JSON.parse(ev.data);M=z||{};S=M.state||{};E=M.exposes||[];reconcilePending();render()}catch{}});es.onerror=()=>{};window.addEventListener('beforeunload',()=>es.close(),{once:true})}catch{}}
poll();startEvents();setInterval(poll,2000)})();
